name: Dart

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write

jobs:
  test-and-merge:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Format check (optional)
      run: dart format . --set-exit-if-changed
      
    - name: Analyze project source
      run: flutter analyze --no-fatal-infos
      
    # - name: Run tests
    #   run: flutter test
    
    # - name: Build APK (release)
    #   run: flutter build apk --release
      
    # - name: Upload APK artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: app-release-apk
    #     path: build/app/outputs/flutter-apk/app-release.apk
        
    - name: Auto merge to main
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout main
        git merge develop
        git push origin main
