name: Dart

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  test-and-merge:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    # - name: Run tests
    #   run: flutter test
      
    - name: Auto merge to main
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout main
        git merge develop
        git push origin main
